import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Card1 from '../components/Cards/Card1';

const data = {
  sections: [
    {
      title: 'News',
      link: '/news',
      image:
        'https://images.pexels.com/photos/9469733/pexels-photo-9469733.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
      alt: '',
    },
    {
      title: 'Vendor Program',
      link: '/vendor-program',
      image:
        'https://images.pexels.com/photos/4527900/pexels-photo-4527900.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'Advocacy',
      link: '/vendor-program',
      image:
        'https://images.pexels.com/photos/4527900/pexels-photo-4527900.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'Empowering People To Work',
      link: '/news',
      image:
        'https://images.pexels.com/photos/4527900/pexels-photo-4527900.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
  ],
  posts: [
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/9469733/pexels-photo-9469733.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/10800242/pexels-photo-10800242.jpeg?cs=srgb&dl=pexels-mary-10800242.jpg&fm=jpg',
    },
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/10810753/pexels-photo-10810753.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/3767370/pexels-photo-3767370.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/5835416/pexels-photo-5835416.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/6353834/pexels-photo-6353834.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/10810753/pexels-photo-10810753.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/3767370/pexels-photo-3767370.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/5835416/pexels-photo-5835416.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/10810753/pexels-photo-10810753.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
    {
      title: 'This is a title',
      imageUrl:
        'https://images.pexels.com/photos/6353834/pexels-photo-6353834.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260',
    },
  ],
};

export default function Home() {
  const { sections, posts } = data;
  return (
    <div>
      <Head>
        <title>Chance For Success | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* start of Hero */}
      <div className="rounded-br-3xl md:rounded-br-40xl overflow-hidden">
        <section className="cover relative bg-gradient-to-r from-red-500 to-orange-400 px-4 sm:px-8 lg:px-16 xl:px-40 2xl:px-64 overflow-hidden py-48 flex items-center">
          <div className="h-full absolute top-0 left-0 right-0 z-0">
            {/* <img
              src="images/agency_hero.jpg"
              alt=""
              className="w-full h-full object-cover opacity-20"
            /> */}
          </div>
          <div className="lg:w-3/4 xl:w-2/4 relative z-10 h-100 lg:mt-16">
            <div>
              <h1 className="text-white text-4xl md:text-5xl xl:text-6xl font-bold leading-tight">
                Article Title
              </h1>
              <p className="text-blue-50 text-xl md:text-2xl leading-snug mt-4">
                Article Sub heading
              </p>
              <a
                href="/marketing.html"
                className="uppercase px-8 py-4 shadow-sm rounded inline-block mt-8 font-semibold hover:bg-blue-500 bg-blue-600 text-white"
              >
                Read more
              </a>
            </div>
          </div>
        </section>
      </div>
      {/* END Hero */}
      {/* start of Sections */}
      <div className=" grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4">
        {sections.map((section, index) => {
          return (
            <Link key={index} href={section.link}>
              <a className="relative block bg-black group max-h-96 max-w-80">
                <div className=" relative">
                  <Image
                    src={section.image}
                    layout="fill"
                    // className="rounded-md object-cover"
                    className="object-cover relative inset-0 transition-opacity opacity-75  group-hover:opacity-50"
                  />
                  {/* Title */}
                  <div className="relative px-8 flex flex-col h-96 w-80">
                    <p className="text-2xl font-bold text-orange-500 pb-4">
                      {section.title}
                    </p>
                  </div>
                  {/* END Title */}
                </div>
              </a>
            </Link>
          );
        })}
        {sections.map((section, index) => {
          return (
            <Link key={index} href={section.link} className="">
              <a className="relative flex items-end w-full bg-black h-96 group">
                <Image
                  src={section.image}
                  alt="Picture of the author"
                  layout="fill" // required
                  objectFit="cover" // change to suit your needs
                  className="" // just an example
                />
                <div className="relative w-full p-6 tracking-widest text-center text-orange-100 transition-colors bg-orange-700 sm:w-[95%] group-hover:bg-black">
                  <strong className="text-lg uppercase">{section.title}</strong>
                  {/* <p className="mt-1 text-xs font-medium uppercase">
                    Design your own
                  </p> */}
                </div>
              </a>
            </Link>
          );
        })}
        {sections.map((section, index) => {
          return (
            <Link key={index} href={section.link} className="">
              <a className="relative block bg-black group" href="">
                {/* <img
                  className="absolute inset-0 object-cover w-full h-full transition-opacity opacity-75  group-hover:opacity-50"
                  src="https://www.hyperui.dev/photos/man-6.jpeg"
                  alt=""
                /> */}
                <Image
                  src={section.image}
                  alt="Picture of the author"
                  layout="fill" // required
                  objectFit="cover" // change to suit your needs
                  className="" // just an example
                />
                <div className="relative">
                  {/* <p className="text-sm font-medium tracking-widest text-orange-500 uppercase">
                    {section.title}
                  </p> */}
                  <p className="text-2xl font-bold text-orange-100 py-4 pl-4">
                    {section.title}
                  </p>
                  <div className="mt-64">
                    <div className="transition-all transform translate-y-8 opacity-0  group-hover:opacity-100 group-hover:translate-y-0">
                      {/* <p className="text-sm text-white">
                        Lorem ipsum dolor, sit amet consectetur adipisicing
                        elit. Omnis perferendis hic asperiores quibusdam quidem
                        voluptates doloremque reiciendis nostrum harum.
                        Repudiandae?
                      </p> */}
                    </div>
                  </div>
                </div>
              </a>
            </Link>
          );
        })}
        {/* END of Sections */}
        {/*  */}

        {/*  */}
      </div>
        <section>
          <div className="mx-4 md:mx-auto md:w-11/12 lg:mx-auto lg:w-1/2 ">
            <div>
              {posts.map((post, index) => {
                return <Card1 imageUrl={post.imageUrl} />;
              })}
            </div>
          </div>
        </section>
    </div>
  );
}
